# Generated by Django 4.1.1 on 2022-11-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_split", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rating",
            field=models.CharField(
                choices=[
                    (1, "Very Bad"),
                    (2, "Bad"),
                    (3, "Average"),
                    (4, "Good"),
                    (5, "Excellent"),
                ],
                default=3,
                max_length=20,
            ),
        ),
    ]
