# Generated by Django 4.1.1 on 2022-11-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_split", "0002_alter_user_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="rating",
        ),
        migrations.AlterField(
            model_name="group",
            name="stage",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Formation"), (2, "Group Formed"), (3, "Vierified")],
                default=1,
                max_length=20,
            ),
        ),
    ]
