# Generated by Django 4.1.1 on 2022-11-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_split", "0004_alter_group_admin_passwd_for_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
