# Generated by Django 4.1.1 on 2022-11-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_split", "0006_alter_group_stage_alter_membership_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="stage",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Formation"), (2, "Formed"), (3, "Verified")],
                default=1,
                max_length=20,
            ),
        ),
    ]
