# Generated by Django 4.1.1 on 2022-11-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_split", "0007_alter_group_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="stage",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Formation"), (2, "Formed"), (3, "Verified")], default=1
            ),
        ),
    ]
