# Generated by Django 4.1.1 on 2022-12-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_split", "0008_alter_group_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
